export interface Startup {
  id: string;
  name: string;
  logo: string;
  cohortYear: number;
  sector: string;
  shortDescription: string;
  fullDescription: string;
  founders: string[];
  website: string;
  program: 'acceleration' | 'incubation';
  mentorName?: string;
  mentorQuote?: string;
}

export const startups: Startup[] = [
  {
    id: '1',
    name: 'Proteger AI',
    logo: '/protogear.png',
    cohortYear: 2025,
    sector: 'HealthTech / MedTech',
    shortDescription: 'AI-driven hospital equipment management with predictive failure reduction',
    fullDescription: 'Proteger AI (Vajra) uses advanced AI to optimize hospital asset management and maintenance through predictive analytics. Onboarded 3 medical colleges, expanding in institutional healthcare digitization.',
    founders: ['Mr.Chethan'],
    website: 'https://www.vajra.software',
    program: 'acceleration',
    mentorName: 'Subramanya Chandramouli',
    mentorQuote: 'A compelling product vision with AI-driven solutions for hospital asset management, offering clear differentiation through predictive failure reduction.',
  },
  {
    id: '2',
    name: 'Panjurli Labs',
    logo: '/panjurli.png',
    cohortYear: 2025,
    sector: 'AgriTech',
    shortDescription: 'Clean tech solutions with meaningful environmental impact',
    fullDescription: 'Panjurli Labs develops innovative sustainable solutions with patented technology. Completed outdoor pilot with Pune Government.',
    founders: ['Panjurli Team'],
    website: 'https://panjurlilabs.com/',
    program: 'acceleration',
    mentorName: 'Mr.Subramanya Chandramouli',
    mentorQuote: 'Patented technology with meaningful environmental impact. A revenue-focused approach will accelerate market adoption.',
  },
  {
    id: '3',
    name: 'VividSparks IT Solutions',
    logo: '/vivid.png',
    cohortYear: 2025,
    sector: 'IT Hardware',
    shortDescription: 'Custom GPU computing solutions for innovation',
    fullDescription: 'VividSparks creates customizable GPU computing hardware solutions. Getting purchase orders with 62 Lakhs in funding raised.',
    founders: ['Mr.Vijay Holimath'],
    website: 'https://vividsparks.tech/',
    program: 'acceleration',
    mentorName: 'Mr.Prashant Mandke',
    mentorQuote: 'Demonstrates clarity and practical thinking with strong potential for partnerships.',
  },
  {
    id: '4',
    name: 'Karpine Technologies',
    logo: '/karpine.png',
    cohortYear: 2025,
    sector: 'Blockchain / IoT',
    shortDescription: 'Digital product passports and blockchain supply chain traceability',
    fullDescription: 'Karpine provides blockchain-based digital twin solutions. Tracked over 1M products with Robert Bosch and Parksons Packaging as white label clients.',
    founders: ['Mr.Karpine Team'],
    website: 'https://www.karpine.io/',
    program: 'acceleration',
    mentorName: 'Mr.Praveen Jhajhria',
    mentorQuote: 'Innovative concept with strong tech foundation; requires focused business development.',
  },
  {
    id: '5',
    name: 'Sasyaani',
    logo: '/sasyani.png',
    cohortYear: 2025,
    sector: 'AgriTech',
    shortDescription: 'Eco-friendly solutions for clean water, soil, and air',
    fullDescription: 'Sasyaani develops sustainable products for wastewater treatment. Achieved 85% odor reduction in dairy sector and 70% COD reduction in pharma STP.',
    founders: ['Dr. Ranjani Chitrapur'],
    website: 'http://www.sasyaani.com',
    program: 'acceleration',
    mentorName: 'Mr.Prashant Mandke',
    mentorQuote: 'Demonstrates clarity and practical thinking with strong environmental impact.',
  },
  {
    id: '6',
    name: 'Eikona X',
    logo: '/eikona.png',
    cohortYear: 2025,
    sector: 'HealthTech / MedTech',
    shortDescription: 'AI-powered dental imaging solutions for accurate x-rays',
    fullDescription: 'Eikona X provides software and hardware solutions for dental professionals. Robust academic foundation with technically differentiated product portfolio.',
    founders: ['Dr. Eikona X Team'],
    website: 'https://eikonax.com/',
    program: 'acceleration',
    mentorName: 'Dr. Amrut Kadam',
    mentorQuote: 'Technically differentiated product portfolio positions the company for strong innovation-led growth.',
  },
  {
    id: '7',
    name: 'Mediimpact Healthcare',
    logo: '/medpass.png',
    cohortYear: 2025,
    sector: 'HealthTech / MedTech',
    shortDescription: 'India\'s first health mobile wallet app for digital health transactions',
    fullDescription: 'Mediimpact Healthcare provides Medpass, a digital health platform. Increased business volume by 2X with clear market acceptance.',
    founders: ['Mr.Bharatheesh P.L.'],
    website: 'https://medpashealth.in/about',
    program: 'acceleration',
    mentorName: 'Dr Lakshmi',
    mentorQuote: 'A validated solution with definitive use case in healthcare financial enablement.',
  },
  {
    id: '8',
    name: 'Oscillo Machines',
    logo: '/oscii.png',
    cohortYear: 2025,
    sector: 'AgriTech',
    shortDescription: 'Farm mechanization equipment for modern agriculture',
    fullDescription: 'Oscillo Machines develops farm mechanization equipment. Selling directly to farmers across multiple Indian states.',
    founders: ['Oscillo Team'],
    website: 'http://oscillomachines.com',
    program: 'acceleration',
    mentorName: 'Prashant Mandke',
    mentorQuote: 'Demonstrates clarity and practical thinking with strong rural impact.',
  },
  {
    id: '9',
    name: 'JALODBUST',
    logo: '/jalodust.png',
    cohortYear: 2025,
    sector: 'AgriTech',
    shortDescription: 'Safe, mechanized wet-sanitation solutions',
    fullDescription: 'JALODBUST provides mechanized sanitation through SANI-PRENEUR. Purchased by Thamate NGO and sponsored by ISRO CSR.',
    founders: ['Mr.JALODBUST Team'],
    website: 'https://jalodbust.com',
    program: 'acceleration',
    mentorName: 'Nachiket Nagaraj Acharya',
    mentorQuote: 'Focused founder; needs to enhance customer acquisition strategy for scale.',
  },
  {
    id: '10',
    name: 'Eccentric Online Solutions',
    logo: '/nearly.png',
    cohortYear: 2025,
    sector: 'Manufacturing',
    shortDescription: 'B2B sustainable packaging marketplace',
    fullDescription: 'Eccentric Online Solutions operates NatNearly.com, a B2B vertical marketplace. Approaching 8-10 clients daily with strong momentum.',
    founders: ['Mr.Mohd. Sadroddin'],
    website: 'https://natnearly.com/',
    program: 'acceleration',
    mentorName: 'Gautham Pai D.',
    mentorQuote: 'Strong founder drive and promising B2B sustainability focus.',
  },
  {
    id: '11',
    name: 'Fracktal Works',
    logo: '/Fractal.png',
    cohortYear: 2025,
    sector: 'Manufacturing',
    shortDescription: 'Deep tech additive manufacturing with AI',
    fullDescription: 'Fracktal Works combines hardware, materials science, and AI. Strong presence in education with expansion into adjacent verticals.',
    founders: ['Mr.Fracktal Team'],
    website: 'http://www.fracktal.in',
    program: 'acceleration',
    mentorName: 'Dr Raghunandan',
    mentorQuote: 'Strong hardware and materials capability with consultative selling approach.',
  },
  {
  id: '12',
  name: 'Emys Bionics',
  logo: '/emys.png',
  cohortYear: 2025,
  sector: 'Health-tech',
  shortDescription: 'Improving safety and precision of surgeries through innovative medical technology.',
  fullDescription: 'Emys Bionics is a health-tech startup focused on improving the safety and precision of surgical procedures. The startup has developed a prototype for the Illumicup and has shown strong responsiveness to market feedback, demonstrating the founders’ ability to pivot quickly.',
  founders: ['Emys Bionics Team'],
  website: 'https://emysbionics.com/',
  program: 'acceleration',
  mentorName: 'Jagan K',
  mentorQuote: 'Highly receptive to market feedback and willing to pivot swiftly – a strong indicator of founder agility.'
  },
  {
  id: '13',
  name: 'nxtQ Private Limited',
  logo: '/nxt.png',
  cohortYear: 2025,
  sector: 'Health Tech',
  shortDescription: 'Wearable sensor-based movement analysis technology for healthcare and elderly care.',
  fullDescription: 'nxtQ Private Limited develops wearable sensor-based solutions for movement analysis, addressing elderly care and neuromotor health needs. The startup has gained traction by winning the TDP9 grant from TiH IIT Bombay and is working toward clinical-grade validation of its technology.',
  founders: ['nxtQ Private Limited Team'],
  website: 'https://www.movementform.in',
  program: 'acceleration',
  mentorName: 'Sriram S L',
  mentorQuote: 'Niche yet critical tech addressing elderly care and neuromotor needs. Agile team with compliance readiness and a pathway toward clinical-grade validation.'
  },
  
  
  
];
